In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
lajas = pd.read_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\2022_laja_aggregation.xlsx',
                          sheet_name='Sheet1', header=0)

In [3]:
lajas

,Name of initiative,Confidence,F6.10b_C2 - Name of jurisdiction or landscape area
0,name_co_864173,uncertain,"Buenos Aires, Santa Fe, Entre Rios."
1,name_co_39880,uncertain,"Mid Central Region, Cordoba, La Pampa"
2,name_co_2414,uncertain,New South Wales and Victoria states
3,name_co_40250,uncertain,Southeast region
4,name_co_2269,uncertain,"Kushtia, Bandarban, Cox's Bazar, Chittagong Hi..."
...,...,...,...
233,name_co_19325_2,uncertain,U.S. Midwest
234,name_co_3732,uncertain,United States
235,name_co_20571_4,partial,United States
236,name_co_4053,uncertain,United States of America
237,name_co_39880_2,uncertain,"San Jose, Canelones"

In [4]:
test_pivot = pd.read_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\2022_laja_aggregation.xlsx',
                          sheet_name='test', header=0)
test_pivot

       Name   Company  Income  Expenses
0    Alfred       ABC   20000     10000
1    Arnold       ABC   35000     20000
2    Benoit       ABC   45000     15000
3    Corbin  McKinsey   75000     50000
4   Demitri   Polgate   65000     45000
5     Elnor   Polgate   66000     30000
6    Ghibli   Polgate   70000     20000
7  Hannover  McKinsey   80000     60000
8   Jacques  McKinsey   85000     57000

In [5]:
testing_pivot = pd.pivot_table(data=test_pivot, index='Company', values='Income')
print(testing_pivot)

                Income
Company
ABC       33333.333333
McKinsey  80000.000000
Polgate   67000.000000

In [6]:
testing_pivot = pd.pivot_table(data=test_pivot, index='Company', aggfunc=['mean','sum'])
print(testing_pivot)

                  mean                    sum
              Expenses        Income Expenses  Income
Company
ABC       15000.000000  33333.333333    45000  100000
McKinsey  55666.666667  80000.000000   167000  240000
Polgate   31666.666667  67000.000000    95000  201000

In [7]:
testing_pivot = pd.pivot_table(data=test_pivot, index='Company', aggfunc={'Income':'sum','Expenses':'mean'})
testing_pivot = testing_pivot.rename(columns = {'Expenses':'Avg Expenses','Income':'Total Income'})
print(testing_pivot)

          Avg Expenses  Total Income
Company
ABC       15000.000000        100000
McKinsey  55666.666667        240000
Polgate   31666.666667        201000

In [8]:
testing_pivot = pd.pivot_table(data=test_pivot, index='Company', values='Name', aggfunc=', '.join)
print(testing_pivot)

                               Name
Company
ABC          Alfred, Arnold, Benoit
McKinsey  Corbin, Hannover, Jacques
Polgate      Demitri, Elnor, Ghibli

In [9]:
laja_test = pd.read_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\2022_laja_aggregation.xlsx',
                          sheet_name='laja_test', header=0)
laja_test

,Organization,Primary activity,F6.10b_C1 - Country/Area,F6.10b_C5 - Forest risk commodities relevant to this landscape/jurisdictional approach,F6.10b_C10 - Implementation partner(s),F6.10b_C15_Provide details of your engagement with landscape/jurisdictional approaches to sustainable land use during the reporting year. - Type of assessment framework,Name of initiative,Confidence
0,Colgate Palmolive Company,Personal care & household products,Indonesia,Palm oil,"Earthworm Foundation, with the support of fina...","Other, please specify: Unknown",Earthworm Aceh,confident
1,Avril,Oilseed processing,Indonesia,Palm oil,Earthworm Foundation,No assessment framework in place,Earthworm Aceh,confident
2,The Hershey Company,Other food processing,Indonesia,Palm oil,Earthworm Foundation,NaN,Earthworm Aceh,confident
3,Reckitt Benckiser,Personal care & household products,Indonesia,Palm oil,Earthworm Foundation,Commodities Jurisdictions Approach,Earthworm Aceh,confident
4,Clorox Company,Personal care & household products,Indonesia,Palm oil,The Earthworm Foundation's Aceh Landscape prog...,Commodities Jurisdictions Approach,Earthworm Aceh,confident
5,FUJI OIL HOLDINGS INC.,Other food processing,Indonesia,Palm oil; Rubber; Timber products,The APT Landscape Initiative is multi-stakehol...,"Other, please specify: コモディティ管轄アプローチ、特定イニシアチブに...",Earthworm Aceh,confident
6,PT Perum Perhutani,Logging,Indonesia,Timber products,PT. Korea Forestry Promotion Institute,"Other, please specify: Financial evaluation an...",name_co_832841,uncertain
7,Cargill,Sugar,Indonesia,Palm oil,The Siak Pelalawan Landscape Programme is a pr...,"Other, please specify: Landscape Activity Repo...",SPLP,confident
8,Musim Mas Holdings Pte Ltd,Palm oil farming,Indonesia,Palm oil,Musim Mas collaborates with District governmen...,Specific initiative defined framework,SPLP,confident
9,Neste Oyj,Oil & gas refining,Indonesia,Palm oil,"Cargill, L'Oréal, Musim Mas, Neste, PepsiCo, a...","Other, please specify: Landscape activity prog...",SPLP,confident
10,Golden Agri-Resources,Palm oil processing,Indonesia,Palm oil,NaN,Specific initiative defined framework,SPLP,confident
11,L'Oréal,Personal care & household products,Indonesia,Palm oil,"Proforest, Daemeter","Other, please specify: Landscape activity prog...",SPLP,confident
12,Danone,Dairy & egg products,Indonesia,Palm oil,The coalition is formed of member companies (...,"Other, please specify: Landscape activity prog...",SPLP,confident
13,"PepsiCo, Inc.",Other food processing,Indonesia,Palm oil,Proforest and Daemeter Consulting,No assessment framework in place,SPLP,confident

In [11]:
laja_org_pivot = pd.pivot_table(data=lajas, index='Name of initiative', values='Organization', aggfunc=', '.join)
laja_org_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_org_pivot.xlsx')
print(laja_org_pivot)

KeyError: 'Organization'

In [13]:
laja_area_pivot = pd.pivot_table(data=lajas, index='Name of initiative', values='F6.10b_C1 - Country/Area', aggfunc=', '.join)
laja_area_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_area_pivot.xlsx')
print(laja_area_pivot)

KeyError: 'F6.10b_C1 - Country/Area'

In [14]:
lajas = lajas.rename(columns = {'F6.10b_C5 - Forest risk commodities relevant to this landscape/jurisdictional approach':'Commodity'})
laja_commod_pivot = pd.pivot_table(data=lajas, index='Name of initiative', values='Primary activity', aggfunc=', '.join)
# laja_commod_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_commod_pivot.xlsx')
print(laja_commod_pivot)

KeyError: 'Primary activity'

In [ ]:
laja_subset = lajas[['Name of initiative', 'Commodity','Organization']]
laja_subset

In [ ]:
laja_subset.dtypes

In [ ]:
laja_subset = laja_subset.astype(str)
laja_subset.dtypes

In [ ]:
laja_commod_pivot = pd.pivot_table(data=laja_subset, index='Name of initiative', values='Commodity', aggfunc=', '.join)
laja_commod_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_commod_pivot.xlsx')
print(laja_commod_pivot)

In [ ]:
laja_subset = lajas[['Name of initiative', 'F6.10b_C10 - Implementation partner(s)','Organization']]
laja_subset = laja_subset.rename(columns = {'F6.10b_C10 - Implementation partner(s)':'Partners'})
laja_subset = laja_subset.astype(str)
laja_subset.dtypes

laja_partner_pivot = pd.pivot_table(data=laja_subset, index='Name of initiative', values='Partners', aggfunc=', '.join)
laja_partner_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_partner_pivot.xlsx')
print(laja_partner_pivot)

In [ ]:
more_laja = pd.read_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\2022_laja_aggregation.xlsx',
                          sheet_name='Sheet1', header=0)
more_laja

In [ ]:
# another way?

test_pivot = test_dataframe.groupby('initiative_name').agg({'companies':', '.join})
print(test_pivot)