In [4]:
import numpy as np
import pandas as pd
laja_data = pd.read_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\2022_laja_aggregation.xlsx',
                          sheet_name='Sheet1', header=0)
laja_data

,Name of initiative,Confidence,F6.10b_C2 - Name of jurisdiction or landscape area
0,name_co_864173,uncertain,"Buenos Aires, Santa Fe, Entre Rios."
1,name_co_39880,uncertain,"Mid Central Region, Cordoba, La Pampa"
2,name_co_2414,uncertain,New South Wales and Victoria states
3,name_co_40250,uncertain,Southeast region
4,name_co_2269,uncertain,"Kushtia, Bandarban, Cox's Bazar, Chittagong Hi..."
...,...,...,...
233,name_co_19325_2,uncertain,U.S. Midwest
234,name_co_3732,uncertain,United States
235,name_co_20571_4,partial,United States
236,name_co_4053,uncertain,United States of America
237,name_co_39880_2,uncertain,"San Jose, Canelones"

In [5]:
laja_data = laja_data.rename(columns={'F6.10b_C2 - Name of jurisdiction or landscape area':'Area'})
laja_data

,Name of initiative,Confidence,Area
0,name_co_864173,uncertain,"Buenos Aires, Santa Fe, Entre Rios."
1,name_co_39880,uncertain,"Mid Central Region, Cordoba, La Pampa"
2,name_co_2414,uncertain,New South Wales and Victoria states
3,name_co_40250,uncertain,Southeast region
4,name_co_2269,uncertain,"Kushtia, Bandarban, Cox's Bazar, Chittagong Hi..."
...,...,...,...
233,name_co_19325_2,uncertain,U.S. Midwest
234,name_co_3732,uncertain,United States
235,name_co_20571_4,partial,United States
236,name_co_4053,uncertain,United States of America
237,name_co_39880_2,uncertain,"San Jose, Canelones"

In [7]:
laja_data = laja_data.astype(str)
laja_data.dtypes

Name of initiative    object
Confidence            object
Area                  object
dtype: object

In [9]:
laja_area_pivot = pd.pivot_table(data=laja_data, index='Name of initiative', values='Area', aggfunc=', '.join)
laja_area_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_area_pivot.xlsx')
print(laja_area_pivot)

                                                                                                 Area
Name of initiative
*Mondi Water Stewardship Partnership                                             uMhlathuze catchment
Aceh Smallholders Hub_1                                                                          Aceh
Aceh Smallholders Hub_2                                                                  Aceh Singkil
Aceh Tamiang PPI Compact                                        Aceh Tamiang and Aceh Timur Districts
Araucaria Conservation Programme                    Santa Catarina and Paraná located within the n...
...                                                                                               ...
name_co_9336_2                                                                               Honduras
name_co_9730                                                                           Bioma Pantanal
name_co_9829                                                                                    Sabah
repeat_Casino_Cia                                   This project covers all direct supply of cattl...
Área Integrada de Gestão da Paisagem (AIGP) Alv...  Área Integrada de Gestão da Paisagem (AIGP) Al...

[195 rows x 1 columns]

In [11]:
laja_confidence_pivot = pd.pivot_table(data=laja_data, index='Name of initiative', values='Confidence', aggfunc=', '.join)
laja_confidence_pivot.to_excel(r'C:\Users\David.Kosciulek\Comp Documents\jupyter\laja_aggs\laja_confidence_pivot.xlsx')
print(laja_confidence_pivot)

                                                              Confidence
Name of initiative
*Mondi Water Stewardship Partnership                           confident
Aceh Smallholders Hub_1                                        confident
Aceh Smallholders Hub_2                                        uncertain
Aceh Tamiang PPI Compact                                       confident
Araucaria Conservation Programme                               uncertain
...                                                                  ...
name_co_9336_2                                                 uncertain
name_co_9730                                                   uncertain
name_co_9829                                                   uncertain
repeat_Casino_Cia                                   uncertain, uncertain
Área Integrada de Gestão da Paisagem (AIGP) Alv...             confident

[195 rows x 1 columns]